`timescale 1ns/1ps
`default_nettype none

/*
 * ============================================================
 * File        : sbox.sv
 * Description : AES-128 Boolean/GF logic S-box
 *
 * Function:
 *   Implements the AES S-box without using a lookup table.
 *
 * AES S-box operation:
 *   1. Take multiplicative inverse in GF(2^8).
 *   2. Apply AES affine transformation.
 *
 * Optimized design choice:`timescale 1ns/1ps
`default_nettype none

/*
 * ============================================================
 * File        : sbox.sv
 * Description : AES-128 Boolean/GF logic S-box
 *
 * Function:
 *   Implements the AES S-box without using a lookup table.
 *
 * AES S-box operation:
 *   The AES S-box is not just a simple substitution table.
 *   Mathematically, it performs two steps:
 *
 *     1. Multiplicative inverse in GF(2^8)
 *     2. AES affine transformation
 *
 *   Therefore:
 *
 *     out_byte = affine_transform(gf_inverse(in_byte))
 *
 * Optimized design choice:
 *   - The baseline design uses a 256-entry lookup table.
 *   - This optimized design computes the S-box output using
 *     combinational GF arithmetic and Boolean XOR logic.
 *   - This supports the chip-area reduction objective because
 *     it avoids storing all 256 S-box values.
 *
 * Important:
 *   - The module name and ports are kept the same as the baseline
 *     lookup-table S-box.
 *   - This allows sub_bytes and key_expansion to reuse the same
 *     S-box interface without changing their port connections.
 *
 * Notes:
 *   - In GF(2^8), 8'h00 has no multiplicative inverse.
 *   - AES defines inverse(00) as 00.
 *   - After the affine transformation, 00 maps to 63.
 *   - Therefore, AES S-box[00] = 8'h63.
 * ============================================================
 */

module sbox
(
    // Input byte before AES S-box substitution.
    input  logic [7:0] in_byte,

    // Output byte after AES S-box substitution.
    output logic [7:0] out_byte
);

    /*
     * inv_byte stores the multiplicative inverse of in_byte in
     * AES GF(2^8).
     *
     * Example:
     *   If in_byte is non-zero, inv_byte = in_byte^(-1).
     *   If in_byte is zero, inv_byte = 8'h00.
     */
    logic [7:0] inv_byte;

    /*
     * Compute multiplicative inverse in GF(2^8).
     *
     * This is the first mathematical step of the AES S-box.
     */
    assign inv_byte = gf_inverse(in_byte);

    /*
     * AES affine transformation.
     *
     * This is the second mathematical step of the AES S-box.
     *
     * Each output bit is generated by XORing selected bits of
     * inv_byte and then XORing with one bit of the AES affine
     * constant 8'h63.
     *
     * AES affine constant:
     *   8'h63 = 0110_0011
     *
     * Bit ordering:
     *   inv_byte[0] is the least significant bit.
     *   out_byte[0] is the least significant bit.
     *
     * These equations implement:
     *
     *   b'[i] = b[i] XOR b[(i+4) mod 8] XOR b[(i+5) mod 8]
     *           XOR b[(i+6) mod 8] XOR b[(i+7) mod 8] XOR c[i]
     *
     * where:
     *   b  = inv_byte
     *   b' = out_byte
     *   c  = 8'h63
     */
    always_comb begin
        out_byte[0] = inv_byte[0] ^ inv_byte[4] ^ inv_byte[5] ^ inv_byte[6] ^ inv_byte[7] ^ 1'b1;
        out_byte[1] = inv_byte[1] ^ inv_byte[5] ^ inv_byte[6] ^ inv_byte[7] ^ inv_byte[0] ^ 1'b1;
        out_byte[2] = inv_byte[2] ^ inv_byte[6] ^ inv_byte[7] ^ inv_byte[0] ^ inv_byte[1] ^ 1'b0;
        out_byte[3] = inv_byte[3] ^ inv_byte[7] ^ inv_byte[0] ^ inv_byte[1] ^ inv_byte[2] ^ 1'b0;
        out_byte[4] = inv_byte[4] ^ inv_byte[0] ^ inv_byte[1] ^ inv_byte[2] ^ inv_byte[3] ^ 1'b0;
        out_byte[5] = inv_byte[5] ^ inv_byte[1] ^ inv_byte[2] ^ inv_byte[3] ^ inv_byte[4] ^ 1'b1;
        out_byte[6] = inv_byte[6] ^ inv_byte[2] ^ inv_byte[3] ^ inv_byte[4] ^ inv_byte[5] ^ 1'b1;
        out_byte[7] = inv_byte[7] ^ inv_byte[3] ^ inv_byte[4] ^ inv_byte[5] ^ inv_byte[6] ^ 1'b0;
    end

    /*
     * ========================================================
     * Function    : gf_inverse
     * Description : Multiplicative inverse in AES GF(2^8)
     *
     * Function:
     *   Calculates a^-1 in AES GF(2^8).
     *
     * AES finite field:
     *   GF(2^8) using irreducible polynomial:
     *
     *     x^8 + x^4 + x^3 + x + 1
     *
     * Reduction constant:
     *   8'h1b
     *
     * Method:
     *   In GF(2^8), every non-zero element satisfies:
     *
     *     a^255 = 1
     *
     *   Therefore:
     *
     *     a^-1 = a^254
     *
     *   This function computes a^254 using repeated squaring and
     *   multiplication.
     *
     * Exponentiation chain:
     *   a2   = a^2
     *   a4   = a^4
     *   a8   = a^8
     *   a16  = a^16
     *   a32  = a^32
     *   a64  = a^64
     *   a128 = a^128
     *
     *   a254 = a128 * a64 * a32 * a16 * a8 * a4 * a2
     *
     * Special case:
     *   AES defines inverse(00) = 00.
     * ========================================================
     */
    function automatic logic [7:0] gf_inverse
    (
        input logic [7:0] a
    );
        logic [7:0] a2;
        logic [7:0] a4;
        logic [7:0] a8;
        logic [7:0] a16;
        logic [7:0] a32;
        logic [7:0] a64;
        logic [7:0] a128;

        logic [7:0] result;

        begin
            /*
             * AES special case:
             * 0 has no inverse, so inverse(0) is defined as 0.
             */
            if (a == 8'h00) begin
                gf_inverse = 8'h00;
            end

            else begin
                /*
                 * Repeated squaring:
                 *
                 * Each line squares the previous result in GF(2^8).
                 */
                a2   = gf_mul(a,    a);
                a4   = gf_mul(a2,   a2);
                a8   = gf_mul(a4,   a4);
                a16  = gf_mul(a8,   a8);
                a32  = gf_mul(a16,  a16);
                a64  = gf_mul(a32,  a32);
                a128 = gf_mul(a64,  a64);

                /*
                 * Multiply selected powers together to produce a^254.
                 */
                result = gf_mul(a128, a64);
                result = gf_mul(result, a32);
                result = gf_mul(result, a16);
                result = gf_mul(result, a8);
                result = gf_mul(result, a4);
                result = gf_mul(result, a2);

                gf_inverse = result;
            end
        end
    endfunction

    /*
     * ========================================================
     * Function    : gf_mul
     * Description : Multiplication in AES GF(2^8)
     *
     * Function:
     *   Multiplies two 8-bit values in the AES finite field.
     *
     * Method:
     *   Uses shift-and-XOR multiplication.
     *
     * Operation:
     *   - If the current multiplier bit is 1, XOR the current
     *     multiplicand into the product.
     *   - Shift the multiplicand left by one bit.
     *   - If the shift overflows beyond bit 7, reduce using
     *     the AES reduction constant 8'h1b.
     *   - Shift the multiplier right by one bit.
     *
     * Reduction:
     *   The constant 8'h1b represents reduction by the AES
     *   irreducible polynomial:
     *
     *     x^8 + x^4 + x^3 + x + 1
     *
     * Hardware meaning:
     *   This function synthesizes into combinational XOR, shift,
     *   and mux logic.
     * ========================================================
     */
    function automatic logic [7:0] gf_mul
    (
        input logic [7:0] a,
        input logic [7:0] b
    );
        logic [7:0] multiplicand;
        logic [7:0] multiplier;
        logic [7:0] product;
        logic       high_bit;
        integer     i;

        begin
            /*
             * Initialize local variables.
             */
            multiplicand = a;
            multiplier   = b;
            product      = 8'h00;

            /*
             * Process all 8 bits of the multiplier.
             */
            for (i = 0; i < 8; i = i + 1) begin

                /*
                 * If the current least significant multiplier bit is 1,
                 * include the current multiplicand in the product.
                 */
                if (multiplier[0] == 1'b1) begin
                    product = product ^ multiplicand;
                end

                /*
                 * Save the MSB before shifting.
                 *
                 * If this bit is 1, the left shift would overflow the
                 * 8-bit AES field and polynomial reduction is required.
                 */
                high_bit = multiplicand[7];

                /*
                 * Multiply multiplicand by x.
                 */
                multiplicand = multiplicand << 1;

                /*
                 * Apply AES polynomial reduction when overflow occurs.
                 */
                if (high_bit == 1'b1) begin
                    multiplicand = multiplicand ^ 8'h1b;
                end

                /*
                 * Move to the next multiplier bit.
                 */
                multiplier = multiplier >> 1;
            end

            gf_mul = product;
        end
    endfunction

endmodule

`default_nettype wire